# Generated by Django 6.0.4 on 2026-04-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating_2gis', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('positive_percent', models.FloatField(default=0)),
                ('instagram_followers', models.IntegerField(default=0)),
                ('instagram_posts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('image_url', models.URLField(blank=True)),
                ('post_url', models.URLField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('engagement_rate', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('2gis', '2GIS'), ('instagram', 'Instagram')], max_length=20)),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('sentiment', models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный'), ('neutral', 'Нейтральный')], max_length=20)),
                ('date', models.DateField()),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('positive_reviews', models.IntegerField(default=0)),
                ('negative_reviews', models.IntegerField(default=0)),
                ('neutral_reviews', models.IntegerField(default=0)),
                ('instagram_followers', models.IntegerField(default=0)),
                ('avg_engagement', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
